name: Deploy Staging

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-go@v3
        with:
          go-version: '1.19' # The Go version to download (if necessary) and use.

      - run: go mod vendor
      - run: ls

      - name: Copy repository contents via scp
        uses: appleboy/scp-action@master
        env:
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          KEY: ${{ secrets.SSHKEY }}
        with:
          source: '.'
          target: '/var/www/staging.ordermanager.sebacz.cl'

      #- name: Add permission
      #  uses: appleboy/ssh-action@master
      #  with:
      #    host: ${{ secrets.HOST }}
      #    USERNAME: ${{ secrets.USERNAME }}
      #    PORT: ${{ secrets.PORT }}
      #    KEY: ${{ secrets.SSHKEY }}
      #    script: sudo chown -R www-data:www-data /var/www/
